### ISSUE TITLE
Submission form failure (+email not working - related?)

### ISSUE THREAD

**Issue by boazsegev** [rubysec/rubysec.com#11]
I tried filling the "Report a new vulnerability" form on the website and got an error page.

So I tried emailing instead... got a Mail Delivery Subsystem error (address blocked).

I don't know if these things are related.

FYI, the YAML for the issue I was attempting to submit was:

```yaml
---
gem: puma
date: 2019-09-23
url: https://bowild.wordpress.com/2019/09/24/puma-server-a-client-at-a-time-security-issue/
title: DoS vulnerability in Puma with busy clients
description: A small number of busy clients could block Puma. The flaw is cause by the fact that Puma handles all of a clients' events before moving on to further events. Clients that keep producing events could prevent the event loop from progressing.
```
